### PR TITLE
Redesign + tokens

### PR DESCRIPTION
**Pull request by loonywizard**
https://kupibiletru.atlassian.net/browse/SITE-3409

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `22.4.0-SITE-3409-new-fonts-and-colors-e446c2ac`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-c241379f`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-25373f89`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-717a7553`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-75876deb`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-5c956764`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-e6aa8262`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-c4de9d9f`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-741a0cd8`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-8e66dd98`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-69be42ae`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-41e49b56`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-bc493b3d`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-70b21894`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-d638eef1`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-33cecd65`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-e6f18bca`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-e9f62859`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-c10ef73d`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.2-SITE-3409-new-fonts-and-colors-26833284`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-c3230cfa`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-49f773fa`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-602401a1`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-2c2f1246`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-e46e2a1b`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-1702ce8e`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-6846f479`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-b422e895`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-b0fbc572`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-209f4382`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-c29ad3bb`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-63921606`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-d355ccc3`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-13db53b4`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-b23e4035`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-a935e6b2`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-f5e891ba`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-68741a09`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-b65d1c7e`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3409-new-fonts-and-colors-76741598`

**Comment by Kupibilet-System** [comment]
New version of package: `22.6.0-SITE-3409-new-fonts-and-colors-c5fb5f61`

**Comment by Kupibilet-System** [comment]
New version of package: `22.6.0-SITE-3409-new-fonts-and-colors-71250f85`

**Comment by Kupibilet-System** [comment]
New version of package: `22.6.0-SITE-3409-new-fonts-and-colors-3a5982fb`

**Comment by Kupibilet-System** [comment]
New version of package: `22.6.0-SITE-3409-new-fonts-and-colors-aefeb57f`

**Comment by Kupibilet-System** [comment]
New version of package: `22.6.0-SITE-3409-new-fonts-and-colors-98d7f15e`

**Review by zinovev — APPROVED** [review]

**Pull request merged**
