### PR TITLE
SITE-3038/utils-to-ts

### PR DESCRIPTION
**Pull request by privetkometa**

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `18.0.0-SITE-3038-utils-to-ts-a6594348`

**Comment by Kupibilet-System** [comment]
New version of package: `18.0.0-SITE-3038-utils-to-ts-f6198284`

**Comment by Kupibilet-System** [comment]
New version of package: `18.0.0-SITE-3038-utils-to-ts-090486b0`

**Comment by Kupibilet-System** [comment]
New version of package: `18.0.0-SITE-3038-utils-to-ts-70e3e857`

**Comment by Kupibilet-System** [comment]
New version of package: `18.0.0-SITE-3038-utils-to-ts-38dbf265`

**Review by loonywizard — APPROVED** [review]

**Comment by Kupibilet-System** [comment]
New version of package: `18.0.0-SITE-3038-utils-to-ts-39bd7330`

**Comment by Kupibilet-System** [comment]
New version of package: `18.0.0-SITE-3038-utils-to-ts-3e952316`

**Pull request merged**
