### PR TITLE
add url for modal

### PR DESCRIPTION
**Pull request by mr-aibeck**

### CODE REVIEW

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-03437141`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-ceeca876`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-420a06e6`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-92347293`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-5fb9af33`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-fe36097b`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-5bc5cabb`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-edd624e1`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-0fd91e15`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-fb9f56a2`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-0efa7505`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-f064fc38`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-704e626e`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-b82d90ba`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-486d3afb`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-2776f0c5`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-396d5d1f`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-a9b7fde9`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-5eb84b36`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-f8c501c8`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-9dc677c2`

**Comment by 7rulnik** [comment]
New version of package: `4.0.2-feature-modal-url-b5bb2d56`

**Comment by nezed** [comment]
Тут происходит что-то странное и неизвестное мне.
Нужно разбираться

**Comment by nezed** [comment]
Не разобрался, похоже на #222 и #237 
Приношу PR в жертву сатане, во славу дизайна и PM

**Pull request closed without merging**
