### PR TITLE
Site 3030/refactor autocomplete and select

### PR DESCRIPTION
**Pull request by MichaelShipitsyn**

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3030-refactor-autocomplete-and-select-2421b701`

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3030-refactor-autocomplete-and-select-71abd348`

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3030-refactor-autocomplete-and-select-b11df07d`

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3030-refactor-autocomplete-and-select-085651fa`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-57a70153`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-8c7c7c1f`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-d44117c2`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-0db18f15`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-820d4492`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-0fe37607`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-41433287`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-d1d2736f`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-4471a846`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-8a1b9078`

**Comment by Kupibilet-System** [comment]
New version of package: `17.1.0-SITE-3030-refactor-autocomplete-and-select-9955f131`

**Review by loonywizard — APPROVED** [review]

**Pull request merged**
