### PR TITLE
fix page scroll when modal is open

### PR DESCRIPTION
**Pull request by zinovev**
[SITE-3538](https://kupibiletru.atlassian.net/browse/SITE-3538)

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3538-try-fix-scroll-c892408f`

**Review by MichaelShipitsyn — APPROVED** [review]

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3538-try-fix-scroll-820866b2`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3538-try-fix-scroll-882c8625`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3538-try-fix-scroll-b228cd88`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3538-try-fix-scroll-0f6411b1`

**Pull request merged**
