### PR TITLE
remove withResponsive

### PR DESCRIPTION
**Pull request by loonywizard**
https://kupibiletru.atlassian.net/browse/SITE-2510

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.10-remove-with-responsive-01580fe4`

**Review by privetkometa — APPROVED** [review]

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.10-remove-with-responsive-fc11a48f`

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.10-remove-with-responsive-4e2f93c6`

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.13-remove-with-responsive-51549016`

**Pull request merged**
