### PR TITLE
Show checkbox icon when disabled

### PR DESCRIPTION
**Pull request by MichaelShipitsyn**

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `19.2.0-SITE-3188-disable-additional-services-543bf475`

**Comment by Kupibilet-System** [comment]
New version of package: `19.2.0-SITE-3188-disable-additional-services-3ccd4e01`

**Comment by Kupibilet-System** [comment]
New version of package: `20.0.0-SITE-3188-disable-additional-services-2c3aab22`

**Comment by Kupibilet-System** [comment]
New version of package: `20.0.0-SITE-3188-disable-additional-services-bacdd2e8`

**Review by loonywizard — APPROVED** [review]

**Pull request merged**
