### PR TITLE
Add 'secondary' toggler variant.

### PR DESCRIPTION
**Pull request by divoannet**

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.4-SITE-2639-additional-tariff-d13ad195`

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.4-SITE-2639-additional-tariff-78dcd820`

**Review by privetkometa — APPROVED** [review]

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.4-SITE-2639-additional-tariff-682be856`

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.5-SITE-2639-additional-tariff-fad31a4a`

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.5-SITE-2639-additional-tariff-9ad66be9`

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.11-SITE-2639-additional-tariff-0a902506`

**Pull request merged**
