### PR TITLE
Site 3530/button to tokens

### PR DESCRIPTION
**Pull request by MichaelShipitsyn**

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-e0002411`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-999f3d91`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-ed0df01f`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-6bef7d27`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-207c0ed9`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-ed2ac9d7`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-bab5ac17`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-63cf4db4`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-1c449982`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-788de4ad`

**Review by privetkometa — APPROVED** [review]

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-cb8b095e`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-c01d4288`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-58e8bda7`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-0f0016ca`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-fcfe4985`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-747b53f5`

**Comment by Kupibilet-System** [comment]
New version of package: `22.5.3-SITE-3530-button-to-tokens-d7f8f83d`

**Pull request merged**
