### PR TITLE
Style Input success and error states

### PR DESCRIPTION
**Pull request by loonywizard**
https://kupibiletru.atlassian.net/browse/SITE-2992

- Rewrite Input stories with ComponentStoryFormat
- Style Input success and error states

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `13.0.0-SITE-2992-style-input-d1641774`

**Comment by Kupibilet-System** [comment]
New version of package: `13.0.0-SITE-2992-style-input-c21fba16`

**Comment by Kupibilet-System** [comment]
New version of package: `13.0.0-SITE-2992-style-input-23cbdf83`

**Comment by Kupibilet-System** [comment]
New version of package: `13.0.0-SITE-2992-style-input-87270322`

**Review by zinovev — APPROVED** [review]

**Pull request merged**
