### PR TITLE
add babel-plugin-import

### PR DESCRIPTION
**Pull request by yulya9060**

### CODE REVIEW

**Comment by nezed** [comment]
New version of package: `4.5.5-MDT-603-add-one-import-for-all-2ba08a5a`

**Comment by nezed** [comment]
New version of package: `4.5.5-MDT-603-add-one-import-for-all-c214b64a`

**Comment by nezed** [comment]
New version of package: `4.5.5-MDT-603-add-one-import-for-all-f1b1e2b3`

**Comment by nezed** [comment]
New version of package: `4.5.5-MDT-603-add-one-import-for-all-a7955bcb`

**Comment by yulya9060** [comment]
sorry for this PR. it was unnecessary

**Pull request closed without merging**
