### PR TITLE
change button sizes

### PR DESCRIPTION
**Pull request by zinovev**
[SITE-3155](https://kupibiletru.atlassian.net/browse/SITE-3155)

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `19.0.2-SITE-3155-buttons-1f422b2b`

**Comment by Kupibilet-System** [comment]
New version of package: `20.0.1-SITE-3155-buttons-11d6ad88`

**Comment by Kupibilet-System** [comment]
New version of package: `20.0.1-SITE-3155-buttons-41f16bc5`

**Review by loonywizard — APPROVED** [review]

**Comment by Kupibilet-System** [comment]
New version of package: `21.0.0-SITE-3155-buttons-3df37ef6`

**Comment by Kupibilet-System** [comment]
New version of package: `21.0.0-SITE-3155-buttons-d3166da1`

**Comment by Kupibilet-System** [comment]
New version of package: `21.0.0-SITE-3155-buttons-330cdc0f`

**Comment by Kupibilet-System** [comment]
New version of package: `21.0.0-SITE-3155-buttons-2b2a26ec`

**Comment by Kupibilet-System** [comment]
New version of package: `21.0.0-SITE-3155-buttons-ffe52385`

**Comment by Kupibilet-System** [comment]
New version of package: `21.0.0-SITE-3155-buttons-042fa109`

**Comment by Kupibilet-System** [comment]
New version of package: `21.0.0-SITE-3155-buttons-1aae3089`

**Comment by Kupibilet-System** [comment]
New version of package: `21.0.0-SITE-3155-buttons-b4f5abf0`

**Pull request merged**
