### PR TITLE
migrate Slider component to TypeScript

### PR DESCRIPTION
**Pull request by loonywizard**
https://kupibiletru.atlassian.net/browse/SITE-3031

use [rc-slider](https://github.com/react-component/slider/) instead of [rheostat](https://github.com/airbnb/rheostat)

### CODE REVIEW

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3031-migrate-slider-to-ts-78a18343`

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3031-migrate-slider-to-ts-2247bd72`

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3031-migrate-slider-to-ts-23a3409f`

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3031-migrate-slider-to-ts-49f296ca`

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3031-migrate-slider-to-ts-c167004d`

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3031-migrate-slider-to-ts-7c668d24`

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3031-migrate-slider-to-ts-12de8d82`

**Comment by MichaelShipitsyn** [comment]
В storybook не работает `disabled `

**Review by privetkometa — APPROVED** [review]

**Review by loonywizard — COMMENTED** [review]
demo comment

**Comment by Kupibilet-System** [comment]
New version of package: `16.0.0-SITE-3031-migrate-slider-to-ts-8a7ad146`

**Pull request merged**
