### PR TITLE
Site 1847/design fixes in navbar

### PR DESCRIPTION
**Pull request by privetkometa**

### CODE REVIEW

**Comment by nezed** [comment]
New version of package: `6.4.1-SITE-1847-design-fixes-in-navbar-1697d887`

**Comment by nezed** [comment]
New version of package: `6.4.1-SITE-1847-design-fixes-in-navbar-150bc55b`

**Comment by nezed** [comment]
New version of package: `6.5.0-SITE-1847-design-fixes-in-navbar-19f0d84d`

**Comment by nezed** [comment]
New version of package: `6.5.0-SITE-1847-design-fixes-in-navbar-9a1ea4a6`

**Comment by Kupibilet-System** [comment]
New version of package: `8.0.15-SITE-1847-design-fixes-in-navbar-920e8534`

**Pull request merged**
